apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app
  namespace: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
      - name: echo-app-container
        image: ofarag/box-server:latest
        ports:
        - containerPort: 8080

